export const WEBSITELEADSOURCE_REQUEST = "WEBSITELEADSOURCE_REQUEST";
export const WEBSITELEADSOURCE_SUCCESS = "WEBSITELEADSOURCE_SUCCESS";
export const WEBSITELEADSOURCE_FAIL = "WEBSITELEADSOURCE_FAIL";
